### ISSUE TITLE
Warn about possibly uninitialized variables.

### ISSUE THREAD

**Issue by ghost** [php-integrator/atom-linter#24]
When a variable is being used for the first time and there aren't any previous assignments to it, such as:

``` php
$a = 'test';
list($a) = ['test'];
```

We can warn the user that the variable is being used without previously having been initialized.
##

**Comment by Gert-dev** [comment]
Closing this as linting is part of the core and will be merged with the base package. The following tickets will track this:

* https://gitlab.com/php-integrator/core/issues/99
* https://gitlab.com/php-integrator/core/issues/76
* https://gitlab.com/php-integrator/core/issues/78
