### ISSUE TITLE
Report method is deprecated

### ISSUE THREAD

**Issue by hultberg** [php-integrator/atom-linter#38]
Add ability for the linter to report if a method called is deprecated, as PhpStorm is able to. I image this requires some changes in php-integrator-base for exposing methods that are deprecated.
## 

I used some time to figure out what repo this type of request belongs to. I believe this is the right one.
##

**Comment by Gert-dev** [comment]
Sounds like a good idea to me.

It does in fact require some changes in the base package, but also in this package. Either way, I don't expect users to know the internals of the packages, so either location is fine :).

**Comment by Gert-dev** [comment]
Hi again. I've moved this ticket [here](https://gitlab.com/php-integrator/core/issues/103) as linting will be completely handled by the core starting from 3.0.0, to keep the core issues in one location.
