### ISSUE TITLE
Handle null coalescing operator (??)

### ISSUE THREAD

**Issue by kitbrennan90** [php-integrator/atom-linter#46]
One of PHP7s new features is the null coalescing operator: http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

Using this operator currently raises the following error: 
`Syntax error, unexpected '?' on line ...`

**Comment by Gert-dev** [comment]
That's odd, is it raising the error as in a red notification box pops up displaying the error or as in that it is listed in the linter results in the bottom panel?

**Comment by kitbrennan90** [comment]
It is listed in the linter results in the bottom panel

**Comment by Gert-dev** [comment]
Are you by any chance using a PHP 5 binary for indexing (in the settings of the base package)?

**Comment by hultberg** [comment]
@Gert-dev Observing this issue myself. Consider the following code:
```php
<?php

$myArray = [ 'foo', 'bar', 'fooer' ];

echo $myArray[1] ?? 'Can\'t find foo!';
```

... gives me:
<img width="544" alt="screen shot 2016-12-05 at 10 55 04" src="https://cloud.githubusercontent.com/assets/1257913/20880625/4b4b82ba-bad9-11e6-945d-0aa69a7280d6.png">

Versions:
```
OS: MacOS Sierra
Atom: 1.13.0-beta6
PHP: 7.0.13
```

**Comment by kitbrennan90** [comment]
Sorry for not posting an update earlier.

I investigated and my machine was using the PHP5 binary (I run the code inside a PHP7 VM which is why I didn't pick up on it earlier).  Once I upgraded my local installation to PHP7 via Homebrew the issue resolved itself.

**Comment by Gert-dev** [comment]
@kitbrennan90 Great to hear!

@hultberg May I assume that the special ?? symbol in the screenshot is only aesthetical and not a special unicode character :-)? Also, are you by any chance using something like MAMP and its setting to update the local PHP binary? If not, could you try opening up the index.php file and dumping the active PHP version, just to be sure?

I've been using most features of PHP 7 for some time now without issues, hence my suspicion.

**Comment by hultberg** [comment]
@Gert-dev Indeed, decided to investigate and turns out `/usr/bin/php` on my machine is php 5.6, while `/usr/local/bin/php` is the php 7.1.. Fixed in configuration in atom, and now its working!

**Comment by Gert-dev** [comment]
@hultberg Great!
