### ISSUE TITLE
Global Namespace Class not found

### ISSUE THREAD

**Issue by mancioshell** [php-integrator/atom-linter#47]
I use  Slim PHP framework included in my project through composer dependency manager. If in my code initialize Slim Container class, `$container = new \Slim\Container($settings);` linter show me up this error:
`php-integrator-linter Error Slim\Container was not found.`

**Comment by Gert-dev** [comment]
Did you by any chance do a composer install after having set up the project? May I assume that the vendor folder containing the files for `Slim` is also part of the project folder in Atom?

**Comment by Gert-dev** [comment]
Closing this due to its date. Feel free to open a new ticket if this still poses a problem.
