### ISSUE TITLE
Ignore some docblock annotation

### ISSUE THREAD

**Issue by neolao** [php-integrator/atom-linter#50]
Like `@param`, `@return`, etc.

I have annotations for the API documentation generator: `@apiName`, `@apiParam`, etc.

It would be nice to ignore a list of annotations in the settings.

**Comment by Gert-dev** [comment]
I've created a new ticket to follow this up in the core here [1]. I'm likely going to remove this linting altogether since it is more of a nuisance with little benefit than an actual useful feature.

[1] https://gitlab.com/php-integrator/core/issues/110
