### ISSUE TITLE
Suppress 'unknown global function' error

### ISSUE THREAD

**Issue by weirdan** [php-integrator/atom-linter#52]
Assuming I have this code:
```php
if (function_exists('optionalFunction')) {
    optionalFunction();
}
```
Linter currently complains about unknown global function, even though it's not a problem (in this specific case).

**Comment by Gert-dev** [comment]
Hi! I've moved this to [this ticket in the core](https://github.com/php-integrator/core/issues/84) as that's where it needs to be implemented. Thanks for taking the time to post this issue and feel free to subscribe there for updates.
