### ISSUE TITLE
[Feature Request] Full namespaced @param paths

### ISSUE THREAD

**Issue by vinkla** [php-integrator/atom-linter#55]
<img width="739" alt="screen shot 2017-02-23 at 11 04 55 pm" src="https://cloud.githubusercontent.com/assets/499192/23281183/94a889da-fa1c-11e6-9e1b-9830900900e7.png">

It seems we don't support full namespaced paths for the `@param` docblocs. Maybe we could add it it as a new feature? Maybe it is already possible?

**Comment by Gert-dev** [comment]
Sounds like a bug, I've moved it (or rather: reposted it, since GitHub doesn't allow moving) it to the core [here](https://github.com/php-integrator/core/issues/89).

**Comment by vinkla** [comment]
:+1:
