### ISSUE TITLE
Full namespace in docblok

### ISSUE THREAD

**Issue by d0niek** [php-integrator/atom-linter#58]
It is possible to set some flag to use class name or full namespace in @param tag?

**Comment by Gert-dev** [comment]
Not at the moment. Are you asking because you are using class names in the docblock that are differently qualified than the ones in the actual signature? For example:

```php
/**
 * @param \A\B $test
 */
function foo(B $test)
{

}
```

**Comment by d0niek** [comment]
I'm just using full-namespace with docblock

```php
use A\B;

/**
 * @param \A\B $test
 */
function foo(B $test): void
{
}
```

**Comment by Gert-dev** [comment]
I see. In that case, see #55 as well as [1], which will fix this issue once it's implemented. I'll close this since it's a duplicate, but thanks for reporting it anyway!

[1] https://gitlab.com/php-integrator/core/issues/89
