### ISSUE TITLE
Seems like the "boolean" primitive is missing

### ISSUE THREAD

**Issue by jeremy-seipelt** [php-integrator/atom-linter#59]
Seems like integrator throws me an error when i use boolean instead of bool as a type
Here is a screen.
![bildschirmfoto 2017-04-13 um 12 52 42](https://cloud.githubusercontent.com/assets/19816884/25001965/1cf1b9aa-2048-11e7-8436-f6e710ffe8cd.png)

According to [PHPdoc](https://phpdoc.org/docs/latest/guides/types.html) its allowed to use boolean or bool

**Comment by Gert-dev** [comment]
That's true, but as you'll find in [1] and [2], this was done in purpose :-).

[1] https://gitlab.com/php-integrator/core/wikis/The%20Docblock%20Problem%20And%20How%20They%20Are%20Processed#types
[2]  #35
